[tool.poetry]
name = "nutra"
version = "0.1.0"
description = ""
authors = ["you"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
